### ISSUE TITLE
error: can't exec '/usr/bin/make' (No such file or directory)

### ISSUE THREAD

**Issue by ThomasJaeger** [defagos/CoconutKit#19]
I'm getting error:

```
error: can't exec '/usr/bin/make' (No such file or directory)
```

Trying to run any of the demos without success. I'm using XCode 4.5.2 with iPad 6.0 Simulator. Are there any special instructions to get the demo working?

Thank you so much for your time and efforts in sharing your work and knowledge.

**Comment by yosoul93** [comment]
it really helps, thanks!
