### ISSUE TITLE
Stackoverflow in "swizzle_viewDidLoad" when using custom keyboards

### ISSUE THREAD

**Issue by andjash** [defagos/CoconutKit#35]
**Steps to reproduce:**
1) Install on device custom keyboard (Yandex.keyboard or Rainbowkey for example)
2) Create plain project in xcode, setup coconutkit as pod.
3) Add simple UITextView on main screen
4) Launch application and try to enter text in textview with custom keyboard
5) Crash

**Guess:**
Swizzled "viewDidLoad" method called for UIRemoteViewController when actual view is nil. Calling "self.view.bounds.size" cause system to force load view and call viewDidLoad again and so on.

**Comment by defagos** [comment]
I just released version 3.2.1 which fixes which fixes this issue.

Thank you very much for your feedback and clear explanations how to reproduce this issue.

Best regards.
